#!/usr/bin/env sh

# bspwm config file
# by: mawi

# [Import paths]

## Bspwm config path
BSPDIR="$HOME/.config/bspwm"

## Add bspwm scripts to path
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1


xresource() {
	xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

# [Launch apps]

## Color Saturation
vibrant-cli VGA-1 2

# Kill if already running
killall -9 picom polybar sxhkd

# Wallpaper Setter
~/.xbg

# Compositor for X
picom --config ~/.config/picom/bsp-picom.conf &

# bar
polybar &

# Cursor
xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &


# [Bspwm config]

bspc config border_width         1
bspc config window_gap          0
bspc config focused_border_color  $(xresource color12)
bspc config active_border_color   "#808080"
bspc config normal_border_color   "#202020"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding 0
bspc config top_padding 0
bspc config pointer_motion_interval 15 # idk , fixed resize laggy

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc monitor -d 󰨞 󰈹  󰀼  
#bspc monitor -d 1 2 3 4 5 6

# [Bspwm Rules]

bspc rule -a firefox desktop=^2 follow=off
bspc rule -a Spotify desktop=^6 follow=off
bspc rule -a Code desktop=^1 follow=off
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '*:*:Picture-in-Picture' state=floating rectangle=400x225+956+533 sticky=on

declare -a floating=(st-float Pcmanfm Lxappearance 'Firefox:Places')
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done
